version: "3.2"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    network_mode: "host"
    hostname: localhost
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
